{ pkgs, lib, ...}:
{
  nixpkgs.config.allowUnfree = true;
  environment.systemPackages = with pkgs; [
    kakoune
    soundconverter
    pnpm
    ffmpeg
    wget
    firefox
    kitty
    hyprland
    nwg-displays
    discord
    pipewire
    zsh
    vscode
    pavucontrol
    fastfetch
    reaper
    git
    curl
    hyprpaper
    waybar
    wofi
    nfs-utils
    gnome-keyring
    catppuccin-cursors.mochaMauve
    nwg-look
    qmk
    freecad
    steam
    docker
    udiskie
    slurp
    grim
    wl-clipboard
    esptool
    minicom
    playerctl
    #ledfx
    ranger
    picard
    rsgain
    vlc
    termusic
    lrcget
    prusa-slicer
    xlights
    vulkan-tools
    htop
    prismlauncher
    yt-dlp
    nodejs_24
    python3
    busybox
    hardinfo2
    wayland-utils
    kdePackages.sddm-kcm
    kdePackages.partitionmanager
    nixfmt-classic
    krita
    gimp
    libimobiledevice
    ifuse
    libreoffice
    tor-browser
    guitarix
    gxplugins-lv2
    cardinal
    decent-sampler
    lsp-plugins
    calf
    dragonfly-reverb
    inkscape-extensions.silhouette
    inkscape
    jellyfin-tui
    #jellyfin-media-player
  ];
  fonts.packages = with pkgs; [ nerd-fonts.jetbrains-mono jetbrains-mono ];
}
